### ISSUE TITLE
Cannot find embedding files online

### ISSUE THREAD

**Issue by Isminoula** [mengf1/PAL#6]
Hello,

Thanks for the code release!
Did you train your own embeddings or found them on the website?
It seems that there is no file en.emb or nl.emb available on http://128.2.220.95/multilingual 

Thanks,

Ismini

**Comment by mengf1** [comment]
You need to open GZ files. In the files, lines starting with `en:` indicate en embedding and lines starting with `nl:` indicate nl embedding.

**Comment by Isminoula** [comment]
Thanks, got it! Had to open the files and create two smaller ones with the source and target languages.
Btw, I truly enjoyed reading your paper, very well written!

**Comment by begab** [comment]
The data resource mentioned in the readme is no longer available from [http://128.2.220.95/multilingual/data](http://128.2.220.95/multilingual/data).
Do you know its new location or can you maybe mirror those embeddings that were used to be found at that url?
Thanks.
